# TCL File Generated by Component Editor 18.1
# Mon Jul 01 11:02:09 CST 2024
# DO NOT MODIFY


# 
# motor_Ctrl "motor_Ctrl" v1.0
#  2024.07.01.11:02:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module motor_Ctrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME motor_Ctrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME motor_Ctrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL motor_ctrl_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gen_step_pluse.v VERILOG PATH ../../RTL/gen_step_pluse.v
add_fileset_file motor_arbit.v VERILOG PATH ../../RTL/motor_arbit.v
add_fileset_file motor_ctrl_top.v VERILOG PATH ../../RTL/motor_ctrl_top.v TOP_LEVEL_FILE
add_fileset_file motor_reg.v VERILOG PATH ../../RTL/motor_reg.v


# 
# parameters
# 
add_parameter S_MODE INTEGER 0
set_parameter_property S_MODE DEFAULT_VALUE 0
set_parameter_property S_MODE DISPLAY_NAME S_MODE
set_parameter_property S_MODE TYPE INTEGER
set_parameter_property S_MODE UNITS None
set_parameter_property S_MODE HDL_PARAMETER true
add_parameter BIT_A INTEGER 19
set_parameter_property BIT_A DEFAULT_VALUE 19
set_parameter_property BIT_A DISPLAY_NAME BIT_A
set_parameter_property BIT_A TYPE INTEGER
set_parameter_property BIT_A UNITS None
set_parameter_property BIT_A ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BIT_A HDL_PARAMETER true
add_parameter BIT_V INTEGER 19
set_parameter_property BIT_V DEFAULT_VALUE 19
set_parameter_property BIT_V DISPLAY_NAME BIT_V
set_parameter_property BIT_V TYPE INTEGER
set_parameter_property BIT_V UNITS None
set_parameter_property BIT_V ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BIT_V HDL_PARAMETER true
add_parameter BIT_S INTEGER 19
set_parameter_property BIT_S DEFAULT_VALUE 19
set_parameter_property BIT_S DISPLAY_NAME BIT_S
set_parameter_property BIT_S TYPE INTEGER
set_parameter_property BIT_S UNITS None
set_parameter_property BIT_S ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BIT_S HDL_PARAMETER true
add_parameter OPT_LONG INTEGER 2000
set_parameter_property OPT_LONG DEFAULT_VALUE 2000
set_parameter_property OPT_LONG DISPLAY_NAME OPT_LONG
set_parameter_property OPT_LONG TYPE INTEGER
set_parameter_property OPT_LONG UNITS None
set_parameter_property OPT_LONG ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OPT_LONG HDL_PARAMETER true
add_parameter QUIT_LONG INTEGER 200
set_parameter_property QUIT_LONG DEFAULT_VALUE 200
set_parameter_property QUIT_LONG DISPLAY_NAME QUIT_LONG
set_parameter_property QUIT_LONG TYPE INTEGER
set_parameter_property QUIT_LONG UNITS None
set_parameter_property QUIT_LONG ALLOWED_RANGES -2147483648:2147483647
set_parameter_property QUIT_LONG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_address address Input 8
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_write_data writedata Input 32
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_read_data readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset reset_sink
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_enable coe_enable Output 1
add_interface_port conduit_end_0 dirction dirction Output 1
add_interface_port conduit_end_0 limit_signal limit_signal Input 1
add_interface_port conduit_end_0 pulse pulse Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1

